# Generated by Django 4.1.7 on 2023-04-01 21:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pirates', '0002_tesouro_pirata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tesouro',
            name='pirata',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tesouros', to=settings.AUTH_USER_MODEL),
        ),
    ]
